### ISSUE TITLE
Add dates of virtual part of the mobility

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-imobilities#6]
I think that it would be helpful if the receiving university could also provide in the XML response the start and end dates related to the virtual part of the mobility. As far as I know the sending institution has to insert these dates into the Mobility Tool (Beneficiary Module).

**Comment by kamil-olszewski-uw** [comment]
The case is the same as for issue https: erasmus-without-paper/ewp-specs-api-omobilities#43 - we need to think about such fields but it's a little early for that.

**Comment by janinamincer-daszkiewicz** [comment]
For the time being we postpone the decision on additional parameters, like start/end dates of virtual component. We need more feedback on how HEIs will handle these processes internally.
